export const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const asset=(name,alt='',cls='')=>`<img class="${cls}" src="./assets/${name}.png" alt="${alt}" draggable="false">`;
export const icon=(name,cls='')=>`<span class="vector-icon ${cls}" aria-hidden="true" style="--icon:url('./assets/${name}.svg')"></span>`;
export function PrimaryButton(text,action,extra=''){return `<button class="button primary" data-action="${action}" ${extra}>${text}</button>`;}
export function SecondaryButton(text,action){return `<button class="button secondary" data-action="${action}">${text}</button>`;}
export function BottomActions(content,foot=''){return `<footer class="bottom-actions">${content}${foot}</footer>`;}
export function Header(){return '<header class="brand"><span aria-hidden="true">◆</span> NovaLend</header>';}
export function ProgressIndicator(step,label){return `<nav class="progress-row" aria-label="Step ${step} of 3. ${label}."><button class="back" data-action="back" aria-label="Go back">‹</button><div class="progress" aria-hidden="true">${[1,2,3].map(n=>`<span class="${n<=step?'filled':''}"></span>`).join('')}</div><span class="step">Step ${step} of 3</span></nav>`;}
export function MobileShell(content,{step=0,label='',camera=false,splash=false,plain=false}={}){return `<main class="mobile-shell ${camera?'camera-shell':''} ${splash?'splash-shell':''}" aria-label="NovaLend prototype"><div class="status-bar" aria-hidden="true"><b>9:41</b><span>▴▴▴ <span class="wifi">◉</span> ▰</span></div>${!camera&&!splash&&!plain?Header():''}${step?ProgressIndicator(step,label):''}${content}${!camera&&!splash?'<div class="home-indicator" aria-hidden="true"></div>':''}</main>`;}
export function FormField(label,id,type,value,placeholder,extra=''){return `<div class="field"><label for="${id}">${label}</label><input id="${id}" name="${id}" type="${type}" value="${escape(value||'')}" placeholder="${placeholder}" ${extra}></div>`;}
export const idTypes=['National ID',"Driver’s Licence",'Passport'];
export function IDSelectionCard(type,index,selected){const descriptions=['e.g. NIN card',"Nigerian driver’s licence",'International passport'];return `<label class="id-card ${selected===type?'selected':''}"><span class="detail-icon" aria-hidden="true">${icon(['id-card','wallet-cards','globe'][index])}</span><span><strong>${type}</strong><small>${descriptions[index]}</small></span><input type="radio" name="idType" value="${type}" ${selected===type?'checked':''}></label>`;}
export function ErrorState({icon,title,body,buttons,note=''}){return `<section class="scroll-content state-content">${stateVisual(icon)}<h1 tabindex="-1">${title}</h1><p>${body}</p></section>${BottomActions(buttons,note?`<p class="network-note">⌁ &nbsp;${note}</p>`:'')}`;}
export function CameraView(kind){const selfie=kind==='selfie';return MobileShell(`<div class="camera-toolbar"><button data-action="${selfie?'selfie-intro':'back'}" aria-label="${selfie?'Cancel selfie':'Go back'}">${selfie?'×':'‹'}</button>${selfie?'':'<span>NovaLend</span>'}<button data-action="flash" aria-label="Toggle simulated flash" aria-pressed="false" class="flash">ϟ</button></div><section class="camera-content"><h1 tabindex="-1">Position your ${selfie?'face':'ID'} within the frame</h1><p>Make sure it's clear, well lit${selfie?'.':' and all corners are visible.'}</p><div class="${selfie?'face-frame':'id-frame'}">${asset(selfie?'selfie-camera':'id-card',selfie?'Sample face for the simulated camera':'Sample ID for the simulated camera')}</div></section><footer class="camera-actions">${selfie?'<button class="camera-small" data-action="selfie-intro"><span>⊠</span>Cancel</button>':''}<div class="shutter-wrap"><button class="shutter" data-action="${selfie?'review-selfie':'review-id'}" aria-label="${selfie?'Capture selfie':'Take photo of ID'}"></button>${selfie?'':'<small>Take photo</small>'}</div>${selfie?'<button class="camera-small" data-action="switch-camera" aria-label="Switch simulated camera"><span>⟳</span>Switch</button>':'<div class="or">or</div><button class="manual-camera" data-action="manual">Enter details manually</button>'}</footer>`,{camera:true});}

export function stateVisual(name){const map={'verified':['circle-check','green'],'capture-error':['camera','red'],'camera-unavailable':['camera-off','blue'],'connection-error':['wifi-off','red'],'upload-error':['circle-alert','red'],'selfie-error':['scan-face','gold']};const item=map[name];return item?`<div class="state-art vector-state ${item[1]}">${icon(item[0])}</div>`:asset(name,'','state-art');}
