import {asset,icon,stateVisual,MobileShell,PrimaryButton as P,SecondaryButton as S,BottomActions as B,FormField,IDSelectionCard,idTypes,ErrorState,CameraView} from './components.js';
const title=(h,p='')=>`<h1 tabindex="-1">${h}</h1>${p?`<p class="intro">${p}</p>`:''}`;
const back=()=>'<button class="back standalone-back" data-action="back" aria-label="Go back">‹</button>';
const checks=items=>`<ul class="checks">${items.map(x=>`<li><span aria-hidden="true">✓</span>${x}</li>`).join('')}</ul>`;
const safe=(long=false)=>`<div class="safe-note"><span aria-hidden="true">${icon("lock-keyhole")}</span><span>Your information is safe and secure with us.${long?'<br>We only use it for this loan application.':''}</span></div>`;
const rows=items=>`<ul class="feature-list">${items.map(([icon,h,p])=>`<li><span class="feature-icon" aria-hidden="true">${typeof icon==='string'?'<span class="vector-icon" aria-hidden="true" style="--icon:url(\'./assets/'+icon+'.svg\')"></span>':icon}</span><div><strong>${h}</strong><p>${p}</p></div></li>`).join('')}</ul>`;
export const screenNames=['splash','onboarding','modules','lend','identity','details','id-select','permission','id-camera','review-id','manual','id-verified','selfie-intro','selfie-camera','review-selfie','verifying','success','id-capture-failed','camera-unavailable','connection-interrupted','upload-failed','selfie-failed'];
const screens={
splash:()=>MobileShell(`<div class="splash-center">${asset('firstbank','FirstBank. Since 1894.','firstbank-logo')}</div><div class="splash-tag"><i></i><em>You First.</em></div>`,{splash:true}),
onboarding:()=>MobileShell(`<div class="onboarding-top"><button class="text-button" data-action="modules">Skip</button></div><section class="scroll-content onboarding"><span class="gold-line"></span>${title('One app.<br>More possibilities.','Bank, save, borrow, manage your business and send money internationally — all in one secure app.')}${asset('onboarding','Woman using a mobile phone. Banking made simpler.','onboarding-photo')}<div class="dots" aria-hidden="true"><i></i><i></i><i></i></div></section>${B(P('Login','modules')+'<p class="signup">Already have an account?<button class="text-button" data-action="modules">Sign up</button></p>')}`,{plain:true}),
modules:()=>MobileShell(`<section class="scroll-content modules"><div class="language"><button class="language-button" data-action="language" aria-expanded="false">◎ English⌄</button><div id="language-menu" hidden><button data-action="language">English</button></div></div>${asset('modules-banner','Greater possibilities for what matters. You First.','module-banner')}<div class="module-list">${[['piggy-bank','NovaSave','Save for what matters'],['hand-coins','NovaLend','Loans & flexible finance'],['briefcase-business','NovaBiz','Tools for your business'],['globe','Remittance','Send & receive globally']].map(([i,h,p])=>`<button class="module" data-action="${h==='NovaLend'?'lend':'unavailable'}"><span class="feature-icon" aria-hidden="true">${icon(i)}</span><span><strong>${h}</strong><small>${p}</small></span><span aria-hidden="true">›</span></button>`).join('')}</div></section>`,{plain:true}),
lend:()=>MobileShell(`<section class="scroll-content lend-content">${back()}${asset('lend-banner','Get the funds you need, when you need them. Simple. Flexible. On your terms.','lend-banner')}${rows([['clock-3','Competitive rates','Tailored to your needs.'],['badge-percent','Flexible repayment','Terms that work for you.'],['shield-check','100% digital process','Apply and get updates in real time.']])}</section>${B(P('Apply for a Loan','identity'))}`),
identity:()=>MobileShell(`<section class="scroll-content">${back()}${title('Verify your identity','To continue with your loan application, we need to verify your identity.')}<div class="steps-card">${[['Confirm your details','Review your personal information.'],['Verify your ID',"Have your ID ready. If the camera doesn’t work, you can enter your details manually."],['Take a selfie',"You will need a working camera and enough light to complete the selfie check."]].map(([h,p],i)=>`<div class="instruction-step"><span>0${i+1}</span><div><strong>${h}</strong><p>${p}</p></div></div>`).join('')}</div></section>${B(P('Continue','details'),safe())}`),
details:()=>MobileShell(`<section class="scroll-content">${title('Confirm your details',"Review your information below to make sure it’s correct before we continue.")}<div class="details-list">${[['user-round','Full name','Ohiya Jacob'],['calendar-days','Date of birth','12 Mar 1995'],['phone','Phone number','0802 123 4567'],['mail','Email address','ohiya.jacob@gmail.com'],['map-pin','Residential address','12 Adeola Odeku Street, Victoria Island, Lagos']].map(([i,l,v])=>`<div class="detail"><span class="detail-icon" aria-hidden="true">${icon(i)}</span><div><small>${l}</small><strong>${v}</strong></div></div>`).join('')}</div></section>${B(P('Continue','id-select')+S('Contact support','support'),safe(true))}`,{step:1,label:'Confirm your details'}),
'id-select':s=>MobileShell(`<section class="scroll-content">${title('Verify your ID','We need to confirm your identity before you continue.')}<fieldset class="id-options"><legend>Select ID type</legend>${idTypes.map((t,i)=>IDSelectionCard(t,i,s.idType)).join('')}</fieldset><div class="inline-actions">${P('Continue','permission')}</div></section>`,{step:2,label:'Verify your ID'}),
permission:()=>MobileShell(`<section class="scroll-content permission-content">${asset('person','','person-art')}${title('Allow camera access','We need camera access to take a<br>photo of your ID.')}<ul class="permission-list"><li><span>${icon("shield-check")}</span>This helps us verify your identity</li><li><span>${icon("shield-check")}</span>Your photos are secure</li><li><span>${icon("shield-check")}</span>You can enter your details manually if you prefer</li></ul></section>${B(P('Allow camera access','id-camera')+S('Enter details manually instead','manual'))}`,{step:2,label:'Verify your ID'}),
'id-camera':()=>CameraView('id'),
'review-id':()=>MobileShell(`<section class="scroll-content">${title('Review your ID','Check that the image is clear and all details are visible.')}${asset('id-card','Sample National ID','review-id-image')}<p class="looks-good">Looks good?</p>${checks(['Image is clear','All details are visible','No glare or blur','All corners are within the frame'])}</section>${B(P('Continue','id-verified')+S('Retake','id-camera'))}`,{step:2,label:'Verify your ID'}),
manual:s=>MobileShell(`<section class="scroll-content">${title('Enter your ID details','Fill in the information as it appears on your ID.')}<form id="manual-form" autocomplete="off"><div class="field"><label for="manual-idType">ID type</label><select id="manual-idType" name="idType">${idTypes.map(t=>`<option ${s.idType===t?'selected':''}>${t}</option>`).join('')}</select></div>${FormField('ID number','idNumber','text',s.form.idNumber,'Enter your ID number','required maxlength="40"')}${FormField('Full name','fullName','text',s.form.fullName,'Enter your full name','required maxlength="100"')}${FormField('Date of birth','dob','date',s.form.dob,'DD/MM/YYYY','required max="'+new Date().toISOString().slice(0,10)+'"')}${P('Continue','submit-manual','type="submit"')}</form></section>`,{step:2,label:'Verify your ID'}),
'id-verified':()=>MobileShell(`<section class="scroll-content state-content verified-content">${stateVisual('verified')}${title('ID verified','Your identity has been confirmed.')}</section>${B(P('Continue to next step','selfie-intro'))}`,{step:2,label:'Verify your ID'}),
'selfie-intro':()=>MobileShell(`<section class="scroll-content selfie-intro">${asset('person','','person-art')}${title('Take a quick selfie',"We’ll use your selfie to complete your identity verification.")}<h2>Before you start</h2>${rows([['sun','Find a well-lit place','Natural light works best'],['user-round','Keep your face clearly visible','Remove sunglasses or face masks'],['smartphone','Hold your phone steady','For a clear, focused photo']])}</section>${B(P('Take selfie','selfie-camera')+S('Do this later','defer'))}`,{step:3,label:'Take a selfie'}),
'selfie-camera':()=>CameraView('selfie'),
'review-selfie':()=>MobileShell(`<section class="scroll-content">${title('Review your selfie','Check that the image is clear and looks like you.')}<button class="selfie-retake" data-action="selfie-camera" aria-label="Retake selfie">${asset('selfie','Sample selfie','review-selfie-image')}</button>${checks(['Your face is clearly visible','The image is clear'])}</section>${B(P('Continue','verifying')+S('Do this later','defer'))}`,{step:3,label:'Take a selfie'}),
verifying:()=>MobileShell(`<section class="scroll-content processing" role="status"><div class="spinner" aria-hidden="true"></div>${title('Verifying your identity...',"We’re securely checking your information. This usually takes a few seconds.")}<ul class="processing-list"><li>♙ &nbsp; Your data is encrypted</li><li>◷ &nbsp; This won’t take long</li><li>▣ &nbsp; Please keep the app open</li></ul></section>`,{step:3,label:'Verifying your identity'}),
success:()=>MobileShell(`<section class="scroll-content state-content success-content">${asset('success','','success-art')}${title("You're all set!","Your identity has been confirmed. Let’s get you one step closer to your goals.")}</section>${B(P('Continue','complete'),'<p class="completion-tag">Secure. Simple. For what’s next.</p>')}`),
'id-capture-failed':()=>MobileShell(ErrorState({icon:'capture-error',title:"We couldn't capture<br>your ID",body:'The image is unclear. Please make sure your ID is well lit and fully within the frame.',buttons:P('Try again','id-camera')+S('Enter details manually instead','manual')}),{step:2,label:'Verify your ID'}),
'camera-unavailable':()=>MobileShell(ErrorState({icon:'camera-unavailable',title:'Camera unavailable',body:"We can’t access your camera at the moment. You can still continue by entering your ID details manually.",buttons:P('Enter details manually','manual')}),{step:2,label:'Verify your ID'}),
'connection-interrupted':()=>MobileShell(ErrorState({icon:'connection-error',title:'Connection interrupted',body:"We couldn’t complete the upload due to a poor connection. Your information has been saved, so you won’t need to start again.",buttons:P('Try again','retry')+S('Continue later','defer'),note:'Connect to a more stable network for a faster and smoother experience.'}),{step:2,label:'Verify your ID'}),
'upload-failed':()=>MobileShell(ErrorState({icon:'upload-error',title:'Upload failed',body:"We still couldn’t complete the upload. This could be due to a weak connection. Your information has been saved.",buttons:P('Try again','retry')+S('Continue later','defer'),note:'Connect to a more stable network for a faster and smoother experience.'}),{step:2,label:'Verify your ID'}),
'selfie-failed':()=>MobileShell(ErrorState({icon:'selfie-error',title:"We couldn't verify<br>your selfie",body:"The image wasn’t clear enough. Please try again in a well-lit place with your face fully visible.",buttons:P('Retake selfie','selfie-camera')+S('Continue later','defer')}),{step:3,label:'Take a selfie'})
};
export function renderScreen(name,state){return screens[name](state);}
